apiVersion: v1
kind: Service
metadata:
  name: istio-experiments-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: istio-experiments
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-experiments-deployment
  labels:
    app: istio-experiments
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-experiments
      version: v1
  template:
    metadata:
      labels:
        app: istio-experiments
        version: v1
    spec:
      containers:
      - name: istio-experiments-v1
        image: istio-experiments:v1
        imagePullPolicy: IfNotPresent
        env:
          - name: VERSION
            value: VERSION-1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command:
              - curl
              - localhost:8080/hello
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
