kind: PersistentVolume
apiVersion: v1
metadata:
  name: istio-experiment-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/istio-experiments/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: istio-experiment-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: istio-experiments-elk
spec:
  ports:
  - port: 8080
    nodePort: 30500
    protocol: TCP
    name: http
  selector:
    app: istio-experiments-elk
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-experiments-elk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: istio-experiments-elk
        version: v1
    spec:
      containers:
      - name: istio-experiments-elk-v1
        image: alzamabar/istio-experiments-elk:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: VERSION
            value: VERSION-1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: istio-experiment-persistent-storage
          mountPath: /var/log/springapps
      volumes:
      - name: istio-experiment-persistent-storage
        persistentVolumeClaim:
          claimName: istio-experiment-pv-claim
