kind: PersistentVolume
apiVersion: v1
metadata:
  name: istio-experiment-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/marcotedone/data/istio-experiments"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: istio-experiment-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi