kind: PersistentVolume
apiVersion: v1
metadata:
  name: istio-experiment-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/istio-experiments/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: istio-experiment-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi