apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-experiments-vs
spec:
  hosts:
    - "*"
  gateways:
    - istio-experiments-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
      - destination:
          port:
            number: 8080
          host: istio-experiments-service